version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: autolot-db
    environment:
      POSTGRES_DB: autolotdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-postgres

volumes:
  postgres-data:

networks:
  spring-postgres: